version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

    env_file:
      - .env

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: bash ./app.sh
    volumes:
      - .:/application_root/
      - static:/application_root/static

  reverse_proxy:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx_configuration/:/etc/nginx/conf.d/
      - static:/static:ro

volumes:
  dbdata:
  static:
