# Generated by Django 4.1.3 on 2022-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPv6Model",
            fields=[
                (
                    "ip_from",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=40,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "ip_to",
                    models.DecimalField(decimal_places=0, max_digits=40, unique=True),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("country_name", models.CharField(max_length=64)),
                ("region_name", models.CharField(max_length=128)),
                ("city_name", models.CharField(max_length=128)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("zip_code", models.CharField(max_length=30)),
                ("time_zone", models.CharField(max_length=8)),
            ],
            options={
                "abstract": False,
                "unique_together": {("ip_from", "ip_to")},
            },
        ),
        migrations.CreateModel(
            name="IPv4Model",
            fields=[
                (
                    "ip_from",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=40,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "ip_to",
                    models.DecimalField(decimal_places=0, max_digits=40, unique=True),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("country_name", models.CharField(max_length=64)),
                ("region_name", models.CharField(max_length=128)),
                ("city_name", models.CharField(max_length=128)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("zip_code", models.CharField(max_length=30)),
                ("time_zone", models.CharField(max_length=8)),
            ],
            options={
                "abstract": False,
                "unique_together": {("ip_from", "ip_to")},
            },
        ),
    ]
